Fix aziot-tpm-sys's C code to log to stderr instead of stdout. (#344)
Cherry-pick from main of 62b03263ea14409daa538d2598e2766b3bdb4089

This means logs are no longer buffered until some arbitrary point in the future
(such as when the process exits). Instead they are immediately printed.

Unfortunately this does not account for logs from the C SDK dependencies,
ie utpm and c-shared, since they use their own logging macro which also writes
using `printf`. So, for example, when running tpmd without a reachable TPM
prints this:

    <6>2021-12-21T00:24:30Z [INFO] (/home/arsing/src/iot-identity-service/tpm/aziot-tpm-sys/azure-iot-hsm-c/src/hsm_log.c:log_init:20) Initialized logging
    Error: Time:Mon Dec 20 16:24:30 2021 File:/home/arsing/src/iot-identity-service/tpm/aziot-tpm-sys/azure-iot-hsm-c/deps/utpm/src/tpm_comm_linux.c Func:tpm_usermode_resmgr_connect Line:268 Failure: No user mode TRM found.
    Error: Time:Mon Dec 20 16:24:30 2021 File:/home/arsing/src/iot-identity-service/tpm/aziot-tpm-sys/azure-iot-hsm-c/deps/utpm/src/tpm_comm_linux.c Func:tpm_comm_create Line:335 Failure: connecting to the TPM device
    Error: Time:Mon Dec 20 16:24:30 2021 File:/home/arsing/src/iot-identity-service/tpm/aziot-tpm-sys/azure-iot-hsm-c/deps/utpm/src/tpm_codec.c Func:Initialize_TPM_Codec Line:256 creating tpm_comm object
    <3>2021-12-21T00:24:30Z [ERR!] (/home/arsing/src/iot-identity-service/tpm/aziot-tpm-sys/azure-iot-hsm-c/src/hsm_client_tpm_device.c:initialize_tpm_device:278) Failure initializeing TPM Codec
    <3>2021-12-21T00:24:30Z [ERR!] (/home/arsing/src/iot-identity-service/tpm/aziot-tpm-sys/azure-iot-hsm-c/src/hsm_client_tpm_device.c:hsm_client_tpm_create:311) Failure initializing tpm device.

... the "ERR!" logs are now printed to stderr, but the "Error:" logs are still
printed to stdout. Unfortunately the latter are still needed for fully
diagnosing issues.

Nevertheless, we'll at least know the aziot-tpm-sys part of the problem
more easily.

Other changes:

- Write the output directly instead of building up a string buffer first.

- Write with Unix newlines instead of Windows newlines.

Ref #233